version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: store-mysql
    restart: always
    environment:
      MYSQL_DATABASE: store_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: store-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/store_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: [ "java","-jar","app.jar" ]

volumes:
  mysql_data:
